# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [6]:
my_arrary= np.array([1,2,3,4])
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
my_3d_array = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [9,10,11,12]]])

print(f'my_array')
print(f'my_2d_array')
print(f'my_3d_array')



my_array
my_2d_array
my_3d_array


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [11]:
new_array = np.array([2,5,4,6])
print(new_array.ndim)

# this prints the shape of the array
print(new_array.shape)

#this prints the size of the array
print(new_array.size)

#this prints the dimension type
print(new_array.dtype)

# this prints the size of the item
print(new_array.item)

#this prints the data for the items
print(new_array.data)

#this prints the number of bytes
#print(new_array.bytes)
# it says that there are no bytes in this array

1
(4,)
4
int64
<built-in method item of numpy.ndarray object at 0x7fd9d54ec800>


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [26]:
# creates a 2x3 array full of zeros
zeros = np.zeros((2, 3))
print(zeros)
# creates an array 1 variable deep with values between 5 - 9
np.arange(5, 9)
print(np.arange)
# gives an array  1x2filled with 1s 
ones = np.ones(1)
print(ones)
#creates an array of 3x4 without initializing values
empty=np.empty(3)
print(empty)
# this creates an array filled with values in a 2x5 shape
full=np.full(2,5)
print(full)
# returns an array that is evenly spaced between 3 and 9
lin =np.linspace(3,9)
print (lin)
#returns random values betwen 0-1
np.random.random

[[0. 0. 0.]
 [0. 0. 0.]]
<built-in function arange>
[1.]
[3. 2. 1.]
[5 5]
[3.         3.12244898 3.24489796 3.36734694 3.48979592 3.6122449
 3.73469388 3.85714286 3.97959184 4.10204082 4.2244898  4.34693878
 4.46938776 4.59183673 4.71428571 4.83673469 4.95918367 5.08163265
 5.20408163 5.32653061 5.44897959 5.57142857 5.69387755 5.81632653
 5.93877551 6.06122449 6.18367347 6.30612245 6.42857143 6.55102041
 6.67346939 6.79591837 6.91836735 7.04081633 7.16326531 7.28571429
 7.40816327 7.53061224 7.65306122 7.7755102  7.89795918 8.02040816
 8.14285714 8.26530612 8.3877551  8.51020408 8.63265306 8.75510204
 8.87755102 9.        ]


<function RandomState.random>

## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [29]:
demo_e = np.ones((2, 3))
demo_f = np.random.random((5, 1, 3))
print(f"demo_e shape: {demo_e.shape}")
print(f"demo_f shape: {demo_f.shape}")

print(demo_e)
print(demo_f)

result = demo_e + demo_f
print(result)
result2 = demo_e * demo_f
print(result2)
result3 = demo_e / demo_f
print(result3)

demo_a = np.ones((2,4))
demo_b = np.random.random((4,1,6))

resulta = demo_a + demo_b

demo_e shape: (2, 3)
demo_f shape: (5, 1, 3)
[[1. 1. 1.]
 [1. 1. 1.]]
[[[0.69924147 0.279241   0.79747854]]

 [[0.9078343  0.46647604 0.7731373 ]]

 [[0.68548156 0.47793999 0.73025913]]

 [[0.47658909 0.21319463 0.67836696]]

 [[0.46658418 0.0831734  0.19244641]]]
[[[1.69924147 1.279241   1.79747854]
  [1.69924147 1.279241   1.79747854]]

 [[1.9078343  1.46647604 1.7731373 ]
  [1.9078343  1.46647604 1.7731373 ]]

 [[1.68548156 1.47793999 1.73025913]
  [1.68548156 1.47793999 1.73025913]]

 [[1.47658909 1.21319463 1.67836696]
  [1.47658909 1.21319463 1.67836696]]

 [[1.46658418 1.0831734  1.19244641]
  [1.46658418 1.0831734  1.19244641]]]
[[[0.69924147 0.279241   0.79747854]
  [0.69924147 0.279241   0.79747854]]

 [[0.9078343  0.46647604 0.7731373 ]
  [0.9078343  0.46647604 0.7731373 ]]

 [[0.68548156 0.47793999 0.73025913]
  [0.68548156 0.47793999 0.73025913]]

 [[0.47658909 0.21319463 0.67836696]
  [0.47658909 0.21319463 0.67836696]]

 [[0.46658418 0.0831734  0.19244641]
  [0.46658418 

ValueError: operands could not be broadcast together with shapes (2,4) (4,1,6) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


demo_1 = np.ones((2,3))
demo_2 = np.ones((4, 4))
demo_3 = np.random.random((2, 1, 5))

np.sum(demo_1)
np.minimum((demo_2), (demo_3))
np.maximum((demo_3))
np.cumsum((demo_1), (demo_3))
np.mean(demo_2)
np.stdv(demo_3)
np.var(demo_3)





## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [36]:
a = [True, True, False, False]
b = [False, False, True, True]

np.logical_or(a, b)
np.logical_and(a,b)
np.logical_not([True, False, 0, 1])





array([False,  True,  True, False])

TypeError: return arrays must be of ArrayType